load('//:buckaroo_macros.bzl', 'buckaroo_deps_from_package')

cxx_binary(
  name = 'test', 
  srcs = [
    'test.cpp', 
  ], 
  deps = buckaroo_deps_from_package('github.com/buckaroo-pm/onqtam-doctest') + [
    '//:rang', 
  ], 
)

cxx_binary(
  name = 'color-test', 
  srcs = [
    'colorTest.cpp', 
  ], 
  deps = buckaroo_deps_from_package('github.com/buckaroo-pm/onqtam-doctest') + [
    '//:rang', 
  ], 
)

cxx_binary(
  name = 'env-term-missing', 
  srcs = [
    'envTermMissing.cpp', 
  ], 
  deps = buckaroo_deps_from_package('github.com/buckaroo-pm/onqtam-doctest') + [
    '//:rang', 
  ], 
)
